"""Initial Migration

Revision ID: 060c1ebfe208
Revises: 11da94e69fa9
Create Date: 2019-09-24 15:00:14.035746

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '060c1ebfe208'
down_revision = '11da94e69fa9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitches', sa.Column('downvotes', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pitches', 'downvotes')
    # ### end Alembic commands ###
