"""adding a pitch model

Revision ID: 56ab3483d3e3
Revises: 0530e3bcc7b3
Create Date: 2019-09-21 20:02:03.752262

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56ab3483d3e3'
down_revision = '0530e3bcc7b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitches', sa.Column('user_id', sa.Integer(), nullable=False))
    op.drop_constraint('pitches_owner_id_fkey', 'pitches', type_='foreignkey')
    op.create_foreign_key(None, 'pitches', 'users', ['user_id'], ['id'])
    op.drop_column('pitches', 'owner_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitches', sa.Column('owner_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'pitches', type_='foreignkey')
    op.create_foreign_key('pitches_owner_id_fkey', 'pitches', 'users', ['owner_id'], ['id'])
    op.drop_column('pitches', 'user_id')
    # ### end Alembic commands ###
