"""Initial Migration

Revision ID: 58b7dbccb212
Revises: 060c1ebfe208
Create Date: 2019-09-24 15:05:28.940357

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58b7dbccb212'
down_revision = '060c1ebfe208'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pitches', 'downvotes')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitches', sa.Column('downvotes', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
